// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BackgroundApiCallWithInterval
{
    public interface IFetchViewController
    {
        void UpdateCurrentTime();
    }

    public partial class FetchViewController : UIViewController, IFetchViewController
    {
        public FetchViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public void UpdateCurrentTime()
        {
            lblCurrentTime.Text = DateTime.Now.ToString("dd MMM yyyy") + "\n" + DateTime.Now.ToString("hh mm");
        }
    }
}
